### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by thisisnajafi** [parch-os/join-requests#17]
# Join request thisisprofnajafi

Hi, I am a full stack web developer with 5 years experience. I would like to help you develop the PARCH.

Skills
- Html
- Css + Sass
- Js
- React
- Vue
- Java
- Cpp
- Php
- Laravel

**Comment by behdanisohrab** [comment]
Hi thanks for being interested  in Parch Linux project. we would be happy to work with you in this project.

you would receive an invite soon.
