### ISSUE TITLE
Join request @Thecode764

### ISSUE THREAD

**Issue by Thecode764** [parch-os/join-requests#20]
# Join request @Thecode764

Skills:
Web developer
Frameworks:
Flask
Bootstrap
Tailwindcss
Languages:
Python
Bash
GO
C
Javascript
CSS
Markup languages:
HTML

**Comment by behdanisohrab** [comment]
Hi, i had reviewed your join request, you would receive an invite to parchlinux soon.

thanks for being interested in Parch Project.
