### ISSUE TITLE
Join Request @tahadostifam

### ISSUE THREAD

**Issue by tahadostifam** [parch-os/join-requests#22]
# Join request @tahadostifam

I'm Taha, a 17-year-old `Software Engineer` and `Full-Stack Web Developer`. As mentioned in the Telegram group, I'm interested in developing the official website for **Parch Linux**,  contributing to both the front-end and back-end.

I guess the website isn't hosted on `GitHub` so i do not know what technology and framework you use to handle it. I usually use `Vuejs` or `Nuxtjs` to develop my project's front-end and we have 3 choices to back-end side.

Since the website likely isn't hosted on GitHub, I'm unsure of the current technology stack. I typically use `Vue.js` or `Nuxt.js` for front-end development, and for the back-end, there are several choices.

While using pure `Node.js` or `Nest.js` is powerful, it might be more complex than necessary for a simpler website. GoLang is a great choice for high-traffic situations, but Parch Linux's website might not require that level of performance.

Ruby on Rails (RoR) is another strong option. It's known for rapid development and scalability, making it ideal for startups. My experience with RoR could be a valuable asset for this project.
Recently i wrote a mini-article about RubyOnRails here at [virgool.io](https://vrgl.ir/Qs9v7).
Reading this article is enough to determine is it good for your startup or not.

I believe I can make a positive contribution to the project.🦄
Thank you for your time and consideration.💚

Best regards,
Taha Dostifam

**Comment by ARANiii** [comment]
Thank you taha ♥️.

**Comment by behdanisohrab** [comment]
@tahadostifam thanks for reaching out about Parch Gnu/Linux. 

we would be happy to work with you in the future.


I would send you an invitation to ParchLinux Github Organization.


Best wishes

Sohrab Behdani
Maintainer of ParchLinux
