### ISSUE TITLE
Shahriar Ghasempour - code

### ISSUE THREAD

**Issue by shahriaarrr** [parch-os/join-requests#7]
# Join request @shahriaarrr
Hello I'm Shahriar Ghasempour
I'm Python developer and my main stack is back-end
I can work with python to write your programs
I'm also know C++ for writing command-line apps and a little bit of Bash and C#
I'm also have good experience in git and Linux
I love contribute in projects and work as team for working on a Linux distro

**Comment by mmdbalkhi** [comment]
Thank you @shahriaarrr, I'll send an invite for you. please check your emails or GitHub's notifications.
